draft: doc
bakaphp/kanvas-doc pull request #3
Opened 2023-11-21 22:23 UTC by FredPeal

2024-01-02 03:17 UTC, SparoHawk requested changes

2024-01-02 03:17 UTC, SparoHawk commented on auth.md
`recieves` is correct. This is no a singular/plurar situation, it is significant to a third-person referral.

Please revert the text as it was.

2024-01-02 03:17 UTC, SparoHawk commented on users.md
`recieves` is correct. This is no a singular/plurar situation, it is significant to a third-person referral.

Please revert the text as it was.

2024-01-02 03:17 UTC, SparoHawk commented on topics.md
**question(blocking):** Topics? Why is this here?

2024-01-02 03:17 UTC, SparoHawk commented on system-modules.md
> +This method enables you to retrieve all system modules and returns a SystemModuleInterface interface.
**suggestion(blocking):** Can we please have a link to the corresponding interface?

2024-01-17 05:56 UTC, FredPeal commented on topics.md
Because Max created the module topics in kanvas ecosystem and it is now in the SDK.

2024-02-14 21:02 UTC, SparoHawk approved these changes

2024-02-14 21:02 UTC, merged